import { collection, doc, serverTimestamp, writeBatch } from "firebase/firestore";
import { db } from "./firebase";

// Helper: quick Unsplash image by keyword (stable enough for dev)
const img = (q) => `https://source.unsplash.com/800x800/?${encodeURIComponent(q)}`;

const products = [
  // TABLE LAMPS
  {
    id: "tbl-ceramic-warm-glow",
    name: "Warm Glow Ceramic Table Lamp",
    price: 799,
    category: "Table Lamps",
    lightQuality: "Warm",
    material: "Ceramic",
    features: ["LED", "Dimmable"],
    imageUrl: img("ceramic table lamp warm"),
    description: "A cozy ceramic lamp for bedside mood lighting and soft ambience.",
    stock: 10,
  },
  {
    id: "tbl-brass-arc-luxe",
    name: "Brass Arc Table Lamp",
    price: 1499,
    category: "Table Lamps",
    lightQuality: "Warm",
    material: "Brass",
    features: ["LED", "Dimmable", "Touch"],
    imageUrl: img("brass table lamp"),
    description: "Premium brass finish with a gentle arc silhouette—clean and luxurious.",
    stock: 10,
  },
  {
    id: "tbl-marble-modern",
    name: "Marble Base Modern Table Lamp",
    price: 1899,
    category: "Table Lamps",
    lightQuality: "Neutral",
    material: "Marble",
    features: ["LED"],
    imageUrl: img("marble base table lamp"),
    description: "Solid marble base with a modern shade—sharp, heavy, and premium.",
    stock: 10,
  },
  {
    id: "tbl-glass-smoke",
    name: "Smoked Glass Table Lamp",
    price: 1299,
    category: "Table Lamps",
    lightQuality: "Warm",
    material: "Glass",
    features: ["LED", "Dimmable"],
    imageUrl: img("smoked glass table lamp"),
    description: "Smoked glass for that high-end hotel vibe—soft glow, big mood.",
    stock: 10,
  },
  {
    id: "tbl-wood-scandi",
    name: "Scandi Wood Table Lamp",
    price: 999,
    category: "Table Lamps",
    lightQuality: "Neutral",
    material: "Wood",
    features: ["LED"],
    imageUrl: img("scandinavian wooden table lamp"),
    description: "Natural wood finish inspired by Nordic interiors—simple and warm.",
    stock: 10,
  },

  // FLOOR LAMPS
  {
    id: "flr-minimalist-metal",
    name: "Minimalist Metal Floor Lamp",
    price: 1299,
    category: "Floor Lamps",
    lightQuality: "Warm",
    material: "Metal",
    features: ["LED"],
    imageUrl: img("minimalist floor lamp"),
    description: "Clean lines, soft light—an easy upgrade for modern living rooms.",
    stock: 10,
  },
  {
    id: "flr-arc-statement",
    name: "Statement Arc Floor Lamp",
    price: 2199,
    category: "Floor Lamps",
    lightQuality: "Warm",
    material: "Metal",
    features: ["LED", "Dimmable"],
    imageUrl: img("arc floor lamp"),
    description: "A bold arc that frames your seating area with premium ambience.",
    stock: 10,
  },
  {
    id: "flr-rattan-boho",
    name: "Rattan Boho Floor Lamp",
    price: 1799,
    category: "Floor Lamps",
    lightQuality: "Warm",
    material: "Rattan",
    features: ["LED"],
    imageUrl: img("rattan floor lamp"),
    description: "Textured rattan shade—warm, cozy, and perfect for a relaxed space.",
    stock: 10,
  },
  {
    id: "flr-brass-tall-luxe",
    name: "Tall Brass Floor Lamp",
    price: 2599,
    category: "Floor Lamps",
    lightQuality: "Neutral",
    material: "Brass",
    features: ["LED", "Dimmable"],
    imageUrl: img("tall brass floor lamp"),
    description: "Premium brass look—subtle flex, strong presence, smooth glow.",
    stock: 10,
  },
  {
    id: "flr-smart-uplight",
    name: "Smart Uplight Floor Lamp",
    price: 2399,
    category: "Floor Lamps",
    lightQuality: "Cool",
    material: "Metal",
    features: ["Smart", "LED", "Dimmable"],
    imageUrl: img("smart floor lamp uplight"),
    description: "Smart control + uplight ambience—set the vibe from your phone.",
    stock: 10,
  },

  // WALL LAMPS
  {
    id: "wal-sconce-brass",
    name: "Brass Wall Sconce",
    price: 899,
    category: "Wall Lamps",
    lightQuality: "Warm",
    material: "Brass",
    features: ["LED"],
    imageUrl: img("brass wall sconce"),
    description: "Minimal brass sconce—perfect for hallways and bedside walls.",
    stock: 10,
  },
  {
    id: "wal-swing-arm",
    name: "Swing-Arm Wall Lamp",
    price: 1099,
    category: "Wall Lamps",
    lightQuality: "Neutral",
    material: "Metal",
    features: ["LED", "Dimmable"],
    imageUrl: img("swing arm wall lamp"),
    description: "Adjustable arm for reading corners—clean, practical, premium.",
    stock: 10,
  },
  {
    id: "wal-ceramic-shell",
    name: "Ceramic Shell Wall Light",
    price: 799,
    category: "Wall Lamps",
    lightQuality: "Warm",
    material: "Ceramic",
    features: ["LED"],
    imageUrl: img("ceramic wall light"),
    description: "Soft ceramic glow—adds texture and warmth without being loud.",
    stock: 10,
  },
  {
    id: "wal-glass-orb",
    name: "Glass Orb Wall Lamp",
    price: 1199,
    category: "Wall Lamps",
    lightQuality: "Neutral",
    material: "Glass",
    features: ["LED", "Dimmable"],
    imageUrl: img("glass orb wall lamp"),
    description: "Glowing orb for that modern gallery look—simple and expensive-feeling.",
    stock: 10,
  },

  // PENDANT LAMPS
  {
    id: "pnd-glass-pendant",
    name: "Clear Glass Pendant",
    price: 1399,
    category: "Pendant Lamps",
    lightQuality: "Neutral",
    material: "Glass",
    features: ["LED"],
    imageUrl: img("clear glass pendant light"),
    description: "Bright and airy pendant—great above kitchens and dining tables.",
    stock: 10,
  },
  {
    id: "pnd-rattan-pendant",
    name: "Rattan Basket Pendant",
    price: 1599,
    category: "Pendant Lamps",
    lightQuality: "Warm",
    material: "Rattan",
    features: ["LED"],
    imageUrl: img("rattan pendant light"),
    description: "Woven texture and warm glow—cozy premium with a relaxed vibe.",
    stock: 10,
  },
  {
    id: "pnd-brass-cylinder",
    name: "Brass Cylinder Pendant",
    price: 1999,
    category: "Pendant Lamps",
    lightQuality: "Warm",
    material: "Brass",
    features: ["LED", "Dimmable"],
    imageUrl: img("brass cylinder pendant light"),
    description: "Slim brass cylinder—modern luxury, strong presence, clean light.",
    stock: 10,
  },
  {
    id: "pnd-ceramic-dome",
    name: "Ceramic Dome Pendant",
    price: 1699,
    category: "Pendant Lamps",
    lightQuality: "Neutral",
    material: "Ceramic",
    features: ["LED"],
    imageUrl: img("ceramic dome pendant light"),
    description: "Matte ceramic dome—minimal, premium, and easy to style.",
    stock: 10,
  },
  {
    id: "pnd-smart-pendant",
    name: "Smart Pendant Light",
    price: 2299,
    category: "Pendant Lamps",
    lightQuality: "Cool",
    material: "Metal",
    features: ["Smart", "LED", "Dimmable"],
    imageUrl: img("smart pendant light"),
    description: "Smart dimming + scenes—set the mood for dinner or deep focus.",
    stock: 10,
  },

  // DESK LAMPS
  {
    id: "dsk-touch-led",
    name: "Touch LED Desk Lamp",
    price: 699,
    category: "Desk Lamps",
    lightQuality: "Cool",
    material: "Metal",
    features: ["LED", "Touch", "Dimmable"],
    imageUrl: img("touch led desk lamp"),
    description: "Tap controls + crisp light—perfect for study sessions and work.",
    stock: 10,
  },
  {
    id: "dsk-wood-lean",
    name: "Wood Lean Desk Lamp",
    price: 899,
    category: "Desk Lamps",
    lightQuality: "Neutral",
    material: "Wood",
    features: ["LED"],
    imageUrl: img("wood desk lamp"),
    description: "A clean wood desk lamp that feels calm and premium without trying.",
    stock: 10,
  },
  {
    id: "dsk-smart-task",
    name: "Smart Task Desk Lamp",
    price: 1299,
    category: "Desk Lamps",
    lightQuality: "Cool",
    material: "Metal",
    features: ["Smart", "LED", "Dimmable"],
    imageUrl: img("smart desk lamp"),
    description: "Smart brightness + schedules—focused light when you need it.",
    stock: 10,
  },
  {
    id: "dsk-glass-minimal",
    name: "Minimal Glass Desk Lamp",
    price: 999,
    category: "Desk Lamps",
    lightQuality: "Warm",
    material: "Glass",
    features: ["LED", "Dimmable"],
    imageUrl: img("minimal glass desk lamp"),
    description: "A premium glass shade with soft warmth—minimal, clean, elegant.",
    stock: 10,
  },

  // HALOGEN + FEATURE VARIATIONS (for your “features” filter)
  {
    id: "tbl-halogen-classic",
    name: "Classic Halogen Table Lamp",
    price: 649,
    category: "Table Lamps",
    lightQuality: "Warm",
    material: "Metal",
    features: ["Halogen"],
    imageUrl: img("classic table lamp"),
    description: "Classic look with halogen brightness—simple and timeless.",
    stock: 10,
  },
  {
    id: "flr-halogen-reading",
    name: "Halogen Reading Floor Lamp",
    price: 1399,
    category: "Floor Lamps",
    lightQuality: "Neutral",
    material: "Metal",
    features: ["Halogen", "Dimmable"],
    imageUrl: img("reading floor lamp"),
    description: "Bright reading lamp with dimming—great for focused corners.",
    stock: 10,
  },
];

export async function seedProducts() {
  const batch = writeBatch(db);
  const colRef = collection(db, "products");

  products.forEach((p) => {
    const ref = doc(colRef, p.id); // stable ID = no duplicates
    batch.set(
      ref,
      {
        name: p.name,
        price: p.price,
        category: p.category,
        lightQuality: p.lightQuality,
        material: p.material,
        features: p.features,
        imageUrl: p.imageUrl,
        description: p.description,
        stock: p.stock,
        isActive: true,
        updatedAt: serverTimestamp(),
      },
      { merge: true }
    );
  });

  await batch.commit();
  console.log(`Seeded/updated ${products.length} products ✅`);
}